var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/research/silent-api/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a4919ac._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_54d1b4a3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f98963d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__cb6eb6f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_research_layout_tsx_8ddef70a._.js")
R.c("server/chunks/ssr/_next-internal_server_app_research_silent-api_page_actions_f8310b2f.js")
R.m(85451)
module.exports=R.m(85451).exports
