var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/research/predictive-aridity-mapping/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__90bce5f2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_f97bf624._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f98963d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__cb6eb6f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_research_layout_tsx_8ddef70a._.js")
R.c("server/chunks/ssr/ce889_server_app_research_predictive-aridity-mapping_page_actions_a405391d.js")
R.m(55643)
module.exports=R.m(55643).exports
